apiVersion: v1
kind: Service
metadata:
  labels:
    app: tileserver
  name: tileserver-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32005
  selector:
    app: tileserver
    service: tileserver-service
  type: NodePort
status:
  loadBalancer: {}