apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-tile-server
  labels:
    app: map-tile-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map-tile-server
  strategy: {}
  template:
    metadata:
      labels:
        app: map-tile-server
    spec:
      containers:
        - name: map-tile-server
          image: maptiler/tileserver-gl
          ports:
            - containerPort: 8080
              name: http
          args: ["--mbtiles", "italy_milan.mbtiles"]
          volumeMounts:
            - name: "mbtiles-storage"
              mountPath: "/data/italy_milan.mbtiles"
      volumes:
        - name: "mbtiles-storage"
          hostPath: 
            path: /persistent-volume/mbtiles/italy_milan.mbtiles
            type: File
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: map-tile-server
  name: tileserver-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30005
  selector:
    app: map-tile-server
  type: NodePort
status:
  loadBalancer: {}
