apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tileserver-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce 
  volumeName: tileserver-storage
  resources:
    requests:
      storage: 1Gi